### ISSUE TITLE
Publish to winget

### ISSUE THREAD

**Issue by dantman** [EDCD/EDMarketConnector#816]
Microsoft is working on a package manager ([winget](https://docs.microsoft.com/en-us/windows/package-manager/winget/)) that allows for automatically installing applications. And there are already lots of applications in it and a collection of websites that let you choose a bunch of applications you use and download a script to install them all.

All it takes to [publish to winget](https://docs.microsoft.com/en-us/windows/package-manager/package/) is to make a PR with a single YAML file to https://github.com/microsoft/winget-pkgs and update the version, installer url, and hash (which `winget hash [file]` will get you) when you publish a new release.

I've already tried out writing the yaml file for the current release:
```yaml
Id: EDCD.EDMarketConnector
Publisher: Elite Dangerous Community Developers
Name: "Elite: Dangerous Market Connector"
Version: 4.1.5
AppMoniker: edmc
Tags: "elite dangerous, mod"
Description: Elite Dangerous Market Connector ("EDMC") is a third-party application for use with Frontier Developments' ("Frontier") game "Elite Dangerous" ("the game"). Its purpose is to facilitate supplying certain game data to, and in some cases retrieving it from, a number of websites and other tools.
Homepage: https://github.com/EDCD/EDMarketConnector/wiki
License: GPL 2.0 or later
LicenseUrl: https://github.com/EDCD/EDMarketConnector/blob/main/LICENSE
InstallerType: msi
Installers:
  - Arch: x86
    Url: https://github.com/EDCD/EDMarketConnector/releases/download/Release%2F4.1.5/EDMarketConnector_win_4.1.5.msi
    Sha256: 4ae6a827583d11f0078a2d46787cf00962dd373a590e45b358164ae9725e9b74
ManifestVersion: 0.1.0
```
